export const BLOG_ERROR = {
  POST_NOT_FOUND: 'BLOG_ERROR_POST_NOT_FOUND',
  SLUG_EXISTS: 'BLOG_ERROR_SLUG_EXISTS',
  CATEGORY_NOT_FOUND: 'BLOG_ERROR_CATEGORY_NOT_FOUND',
  TAG_NOT_FOUND: 'BLOG_ERROR_TAG_NOT_FOUND',
  COMMENT_NOT_FOUND: 'BLOG_ERROR_COMMENT_NOT_FOUND',
} as const;